### PR TITLE
Multiple fixs

### PR DESCRIPTION
**Pull request by Striffly**
There were many bugs in [supersonic2k22](https://github.com/ainsleyclark/squidge/issues?q=is%3Apr+author%3Asupersonic2k22) PR code (a `while(true)` loop in particular), this PR makes fixs to it

### CODE REVIEW

**Comment by ainsleyclark** [comment]
Hey @Striffly, thanks for your PR! If you could just rename the plugin and format the files that would be great.
Thanks!

**Comment by Striffly** [comment]
What are you mean by "rename the plugin" ? Keep the plugin named "Squidge modified" ?<br>
Also, formatting wad done with PHPStorm formatting with EditorConfig enabled. Do you have an example of what is wrong with the formatting that has been done?

**Comment by ainsleyclark** [comment]
Yep if you could change `squidge modified` to `squidge` that would be great.

Don't worry about the formatting, probably set up different on my phpstorm!

**Comment by Striffly** [comment]
Screenshot from 2023-01-25 14-55-46
The renaming is already done here, I don't see where this renaming is not present elsewhere in the code. Can you tell me where you see a renaming to be done?

**Comment by ainsleyclark** [comment]
Ignore, I need coffee.
Thanks for this PR.

**Review by ainsleyclark — APPROVED** [review]

**Pull request merged**
