### PR TITLE
Changes CLI and count of images

### PR DESCRIPTION
**Pull request by supersonic2k22**
I added changes to the name of the required files and added a counter of images. 
## Related Issue
Bug with CLI, counter of images

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by ainsleyclark — APPROVED** [review]

**Comment by ainsleyclark** [comment]
Thanks for this pull.
Can you confirm what changes have been made and if they have been tested?

**Comment by karbivskij** [comment]
You can tested yourself before updating. All my changes in my fork.

вс, 29 мая 2022 г., 14:32 Ainsley Clark ***@***.***>:

**Comment by ainsleyclark** [comment]
@supersonic2k22 will the pull request you opened fix above? Sorry just catching up appreciate the help.

**Comment by ainsleyclark** [comment]
@supersonic2k22 will merge this immediately, but would you mind changing `Squidge modified` back to `Squidge` in `squidge.php`? Thank you!

**Comment by supersonic2k22** [comment]
@ainsleyclark  I can't change in this menu. Maybe you can decline this change?

**Comment by supersonic2k22** [comment]
Hello @ainsleyclark  I created new pull request with changed name of cli to correct work of wp cli with squidge on Linux

**Comment by ainsleyclark** [comment]
Thanks @supersonic2k22!

**Pull request merged**
